spring:
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/mrviesspace?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true&tinyInt1isBit=false&allowMultiQueries=true
    username: weiweiwei
    password: qQUCoiHcWQ3pAuFD
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource